### PR TITLE
docs: update Readme

### PR DESCRIPTION
**Pull request by nanjiangshu**
Clarify which yarn to use and the usage of command.

### CODE REVIEW

**Comment by nanjiangshu** [comment]
I actually don't understand what the command `$ yarn` (without the flag "start <data-file-path") is doing. It it does not generate any real data, then we should remove it.

**Comment by e0** [comment]
@nanjiangshu Thanks for the PR. The `yarn` command is short for `yarn install`. It install the NPM packages under `node_modules`.

**Comment by nanjiangshu** [comment]
Thanks @e0 for clarification! So there are two steps,

The command `$ yarn` installs NPM packages and then
` $ yarn start <path-of-data-file>` generates data.

**Comment by e0** [comment]
> So there are two steps

That's exactly right, we were way too sloppy on the documentation before.

**Review by mihai-sysbio — CHANGES_REQUESTED** [review]
This Readme assumed a lot of prior knowledge, so it's really good to address this. Let's also clarify that while these commands can be run on their own, the output is meaningful only for the deployment pipeline.
Here is the documentation for the [yarn command](https://classic.yarnpkg.com/en/docs/cli/#toc-default-command). It would be good to have this in the Readme too.

**Comment by mihai-sysbio** [comment]
As suggested by @e0 it would be good to add the minimum versions required too.

**Comment by nanjiangshu** [comment]
> This Readme assumed a lot of prior knowledge, so it's really good to address this. Let's also clarify that while these commands can be run on their own, the output is meaningful only for the deployment pipeline.
> Here is the documentation for the [yarn command](https://classic.yarnpkg.com/en/docs/cli/#toc-default-command). It would be good to have this in the Readme too.

This comment is addressed.

**Review by mihai-sysbio — APPROVED** [review]

**Pull request merged**
